In [2]:
%pip install matplotlib
%pip install seaborn

import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt

np.random.seed(518)
#import seaborn as sns

  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 7.3 MB/s eta 0:00:00a 0:00:01
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 11.6 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 7.0 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [matplotlib]7 [matplotlib]
Note: you may need to restart the kernel to use updated packages.
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Note: you may need to restart the kernel to use updated packages.


# Categorical Data Cleaning

In [3]:
categorical_df = pd.read_csv("categorical_dataframe_uncleaned_hannah_nguyen.csv")
categorical_df

Flooring PoolPrivateYN      PropertyType  \
0                        NaN         False       Residential   
1       Carpet,Laminate,Tile         False  ResidentialLease   
2                Carpet,Tile         False  ResidentialLease   
3                        NaN         False       Residential   
4                       Wood         False  ResidentialLease   
...                      ...           ...               ...   
504752           Carpet,Wood          True       Residential   
504753                  Tile         False       Residential   
504754                   NaN         False       Residential   
504755           Carpet,Tile          True       Residential   
504756       Carpet,Laminate         False       Residential   

              PropertySubType           City FireplaceYN       Levels  \
0       SingleFamilyResidence  National City       False          Two   
1       SingleFamilyResidence    Chula Vista        True          Two   
2       SingleFamilyResidence  Newport Beach        True          One   
3       SingleFamilyResidence  National City       False          Two   
4       SingleFamilyResidence   Solana Beach        True  ThreeOrMore   
...                       ...            ...         ...          ...   
504752  SingleFamilyResidence         Corona        True          Two   
504753  SingleFamilyResidence   Yucca Valley        True          One   
504754  SingleFamilyResidence          Hemet        True          One   
504755  SingleFamilyResidence      Riverside        True          One   
504756  SingleFamilyResidence       Stockton        True          One   

       NewConstructionYN  
0                  False  
1                    NaN  
2                  False  
3                  False  
4                    NaN  
...                  ...  
504752             False  
504753             False  
504754             False  
504755             False  
504756               NaN  

[504757 rows x 8 columns]

# Categorical Data null values


In [4]:
print(categorical_df.isnull().sum())

Flooring             187864
PoolPrivateYN         52737
PropertyType              0
PropertySubType           0
City                   2292
FireplaceYN           12125
Levels                67987
NewConstructionYN    101342
dtype: int64


## Flooring


In [5]:
# Checking all unique values
for value in sorted(categorical_df["Flooring"].dropna().unique()):
    print(value)


Bamboo
Bamboo,Brick,Carpet
Bamboo,Brick,Carpet,Laminate,Tile
Bamboo,Brick,Carpet,Stone,Tile
Bamboo,Brick,Tile
Bamboo,Brick,Tile,Wood
Bamboo,Carpet
Bamboo,Carpet,Concrete
Bamboo,Carpet,Concrete,Laminate,SeeRemarks,Stone
Bamboo,Carpet,Concrete,SeeRemarks
Bamboo,Carpet,Concrete,Stone
Bamboo,Carpet,Concrete,Tile
Bamboo,Carpet,Concrete,Tile,Vinyl,Wood
Bamboo,Carpet,Concrete,Wood
Bamboo,Carpet,Laminate
Bamboo,Carpet,Laminate,SeeRemarks
Bamboo,Carpet,Laminate,SeeRemarks,Tile
Bamboo,Carpet,Laminate,SeeRemarks,Tile,Wood
Bamboo,Carpet,Laminate,Stone
Bamboo,Carpet,Laminate,Tile
Bamboo,Carpet,Laminate,Tile,Vinyl
Bamboo,Carpet,Laminate,Tile,Wood
Bamboo,Carpet,Laminate,Vinyl
Bamboo,Carpet,Laminate,Vinyl,Wood
Bamboo,Carpet,Laminate,Wood
Bamboo,Carpet,SeeRemarks
Bamboo,Carpet,SeeRemarks,Stone,Tile
Bamboo,Carpet,SeeRemarks,Stone,Wood
Bamboo,Carpet,SeeRemarks,Tile
Bamboo,Carpet,SeeRemarks,Tile,Wood
Bamboo,Carpet,SeeRemarks,Vinyl
Bamboo,Carpet,SeeRemarks,Wood
Bamboo,Carpet,Stone
Bamboo,Carpet,Stone,Tile


I think I will group values with multiple flooring types into a new category "Mixed". I also see "..." and will be changing it to null values so I could properly fill in the missing values later on. I am considering trying the probability method for assigning the flooring types to the null values.

In [6]:
# Checking the value distribution of 'Flooring'
categorical_df['Flooring'].value_counts()

Flooring
Carpet,Tile                                         37580
Wood                                                35428
Tile,Wood                                           27379
Laminate                                            23445
Carpet,Tile,Wood                                    20304
                                                    ...  
Brick,Concrete,Laminate                                 1
Concrete,Stone,Vinyl,Wood                               1
Bamboo,Carpet,Concrete,Laminate,SeeRemarks,Stone        1
Brick,Concrete,Tile,Wood                                1
Bamboo,Concrete,Laminate,Tile,Wood                      1
Name: count, Length: 355, dtype: int64

In [7]:
# Defining the function to change the flooring names appropriately
def flooring_names(value):
    if pd.isna(value) == True:
        return value
    elif ',' in value:
        return "Mixed"
    else:
        return value
    
    
# Applying it to the column for flooring
categorical_df["Flooring"] = categorical_df["Flooring"].apply(flooring_names)

# Checking the distribution if it was properly applied
categorical_df['Flooring'].value_counts()

Flooring
Mixed         212504
Wood           35428
Laminate       23445
Tile           16112
Carpet         12371
Vinyl          10174
SeeRemarks      4115
Stone           1231
Concrete         996
Bamboo           474
Brick             43
Name: count, dtype: int64

Next, I will fill in the missing values using the probability based on the observed values. Since "Mixed" is a broad category, I am considering not including it in the probability calculations.

In [8]:
# Defining the individual probabilities of the different types excluding 'Mixed'
flooring_count = categorical_df['Flooring'].value_counts()
flooring_count_excluding_mixed = flooring_count.drop('Mixed')
total = flooring_count_excluding_mixed.sum()
flooring_probs = flooring_count_excluding_mixed / total

# Applying it to the missing values
categorical_df['Flooring'] = categorical_df['Flooring'].apply(lambda x: np.random.choice(flooring_probs.index, p = flooring_probs.values) if pd.isna(x) else x)


In [9]:
print(flooring_probs)

Flooring
Wood          0.339384
Laminate      0.224593
Tile          0.154346
Carpet        0.118509
Vinyl         0.097462
SeeRemarks    0.039420
Stone         0.011792
Concrete      0.009541
Bamboo        0.004541
Brick         0.000412
Name: count, dtype: float64


In [10]:
# Checking distribution
categorical_df['Flooring'].value_counts(normalize=True)

Flooring
Mixed         0.421003
Wood          0.196306
Laminate      0.130560
Tile          0.089538
Carpet        0.068051
Vinyl         0.056082
SeeRemarks    0.023078
Stone         0.006932
Concrete      0.005581
Bamboo        0.002637
Brick         0.000232
Name: proportion, dtype: float64

In [11]:
print(categorical_df.isnull().sum())

Flooring                  0
PoolPrivateYN         52737
PropertyType              0
PropertySubType           0
City                   2292
FireplaceYN           12125
Levels                67987
NewConstructionYN    101342
dtype: int64


## PoolPrivateYN

In [12]:
# Checking distribution
categorical_df['PoolPrivateYN'].value_counts()

PoolPrivateYN
False    383053
True      68967
Name: count, dtype: int64

I think I will do something similar to assigning true or false to the missing values based on probabilities.

In [13]:
# Defining the probabilties
pool_probabilities = categorical_df['PoolPrivateYN'].value_counts(normalize = True)
print(pool_probabilities)

# Fill in missing values based on probability
categorical_df['PoolPrivateYN'] = categorical_df['PoolPrivateYN'].apply(lambda x: np.random.choice(pool_probabilities.index, p = pool_probabilities.values) if pd.isna(x) else x)


PoolPrivateYN
False    0.847425
True     0.152575
Name: proportion, dtype: float64


In [14]:
# Checking for distribution and null values
print(categorical_df.isnull().sum())
categorical_df['PoolPrivateYN'].value_counts(normalize=True)

Flooring                  0
PoolPrivateYN             0
PropertyType              0
PropertySubType           0
City                   2292
FireplaceYN           12125
Levels                67987
NewConstructionYN    101342
dtype: int64


PoolPrivateYN
False    0.84756
True     0.15244
Name: proportion, dtype: float64

In [15]:
# Encoding True to 1 and False to 0 to help with training the model
categorical_df['PoolPrivateYN'] = categorical_df['PoolPrivateYN'].map({True: 1, False: 0})
categorical_df['PoolPrivateYN'].value_counts(normalize=True)

PoolPrivateYN
0    0.84756
1    0.15244
Name: proportion, dtype: float64

## City

In [16]:
# Checking all unique values
#for value in sorted(categorical_df["City"].dropna().unique()):
    #print(value)

# print(len(categorical_df['City'].dropna().unique()))

# Standardizing to make everything lowercase and no whitespace
categorical_df['City'] = categorical_df['City'].str.lower().str.strip()
city_counts = categorical_df['City'].value_counts()
#print(city_counts)

# print(city_counts.tail(40))  # top 40 leastfrequent cities

# There are still many cities with little observations, so I will increase the threshold to less than 100
common_cities = city_counts[city_counts > 100].index
categorical_df['City'] = categorical_df['City'].apply(lambda x: x if x in common_cities else 'Other')

# Reassigning city_counts
city_counts = categorical_df['City'].value_counts()
print(city_counts)

# Checking number of observations in 'Other'
other_total = (categorical_df['City'] == 'Other').sum()
print(f'Number of Observations within "Other": {other_total}')

City
los angeles     21342
san diego       17462
Other           14377
san jose        10982
riverside        7679
                ...  
cobb              105
capitola          104
benicia           103
monte sereno      102
arrowbear         101
Name: count, Length: 466, dtype: int64
Number of Observations within "Other": 14377


I checked the unique values and there were roughly 1100 unique city values, so i reduced it down to 460 to remove any city that only had <100 observations, since overfitting could potentially happen if I tried to get the model to remember every detail. The total number of obesrvations within 'Other' is 14377.

The null values were replaced with 'Other' as well, since they only made up a small portion of the total observations (2292).

Next, I will do frequency encoding on the rows to change the city names into numerical format that the machine learning models can understand. Since my cutoff was >100 observations for each city, it is less likely that two or more cities will share the same number of observations. Because I am training with Random Forest, frequency encoding will not be a problem, since it wouldn't assume one city is more important than another just because it had more observations. I will make a new column for the frequency encoding.

In [17]:
# Calculating frequency of each category
city_freq = categorical_df['City'].value_counts()

# Making a new column to store the frequency counts based on City
categorical_df['City_freq'] = categorical_df['City'].map(city_freq)

categorical_df

Flooring  PoolPrivateYN      PropertyType        PropertySubType  \
0          Wood              0       Residential  SingleFamilyResidence   
1         Mixed              0  ResidentialLease  SingleFamilyResidence   
2         Mixed              0  ResidentialLease  SingleFamilyResidence   
3          Wood              0       Residential  SingleFamilyResidence   
4          Wood              0  ResidentialLease  SingleFamilyResidence   
...         ...            ...               ...                    ...   
504752    Mixed              1       Residential  SingleFamilyResidence   
504753     Tile              0       Residential  SingleFamilyResidence   
504754     Wood              0       Residential  SingleFamilyResidence   
504755    Mixed              1       Residential  SingleFamilyResidence   
504756    Mixed              0       Residential  SingleFamilyResidence   

                 City FireplaceYN       Levels NewConstructionYN  City_freq  
0       national city       False          Two             False        395  
1         chula vista        True          Two               NaN       2995  
2       newport beach        True          One             False       1959  
3       national city       False          Two             False        395  
4        solana beach        True  ThreeOrMore               NaN        284  
...               ...         ...          ...               ...        ...  
504752         corona        True          Two             False       4873  
504753   yucca valley        True          One             False       1346  
504754          hemet        True          One             False       4493  
504755      riverside        True          One             False       7679  
504756       stockton        True          One               NaN        658  

[504757 rows x 9 columns]

In [18]:
print(categorical_df.isnull().sum())

Flooring                  0
PoolPrivateYN             0
PropertyType              0
PropertySubType           0
City                      0
FireplaceYN           12125
Levels                67987
NewConstructionYN    101342
City_freq                 0
dtype: int64


## FireplaceYN

In [19]:
# Checking distribution
categorical_df['FireplaceYN'].value_counts()

FireplaceYN
True     366582
False    126050
Name: count, dtype: int64

Similar to PoolPrivateYN, I will fill in the missing values using probabilities.

In [20]:
# Defining the Probabilities
fireplace_probabilities = categorical_df['FireplaceYN'].value_counts(normalize = True)
print(fireplace_probabilities)

# Fill in missing values based on probability
categorical_df['FireplaceYN'] = categorical_df['FireplaceYN'].apply(lambda x: np.random.choice(fireplace_probabilities.index, p = fireplace_probabilities.values) if pd.isna(x) else x)

FireplaceYN
True     0.744129
False    0.255871
Name: proportion, dtype: float64


In [21]:
# Checking for distribution and null values
print(categorical_df.isnull().sum())
categorical_df['FireplaceYN'].value_counts(normalize = True)

Flooring                  0
PoolPrivateYN             0
PropertyType              0
PropertySubType           0
City                      0
FireplaceYN               0
Levels                67987
NewConstructionYN    101342
City_freq                 0
dtype: int64


FireplaceYN
True     0.744148
False    0.255852
Name: proportion, dtype: float64

In [22]:
# Encoding True to 1 and False to 0 to help with training the model
categorical_df['FireplaceYN'] = categorical_df['FireplaceYN'].map({True: 1, False: 0})
categorical_df['FireplaceYN'].value_counts(normalize=True)

FireplaceYN
1    0.744148
0    0.255852
Name: proportion, dtype: float64

## Levels

In [23]:
# Checking distribution
categorical_df['Levels'].value_counts()

Levels
One                               264059
Two                               154611
ThreeOrMore                         9272
MultiSplit                          6300
One,Two                             1037
Two,MultiSplit                       673
ThreeOrMore,MultiSplit               271
One,MultiSplit                       234
Two,ThreeOrMore                      197
One,ThreeOrMore                       87
One,Two,MultiSplit                    13
Two,ThreeOrMore,MultiSplit             6
One,Two,ThreeOrMore                    6
One,Two,ThreeOrMore,MultiSplit         2
One,ThreeOrMore,MultiSplit             2
Name: count, dtype: int64

First, I will fill in the missing values using the probability method from earlier.

I will attempt to split the combinations into multiple binary coding. For example, since every obesrvation is a combination of "One", "Two", "ThreeOrMore", or "MultiSplit", each value will be coded as 1 if they have one of those it, and 0 if not.

In [24]:
# Defining the probabilities
levels_probabilities = categorical_df['Levels'].value_counts(normalize = True)
print(levels_probabilities)

# Fill in the missing values
categorical_df['Levels'] = categorical_df['Levels'].apply(lambda x: np.random.choice(levels_probabilities.index, p = levels_probabilities.values) if pd.isna(x) else x)


Levels
One                               0.604572
Two                               0.353987
ThreeOrMore                       0.021229
MultiSplit                        0.014424
One,Two                           0.002374
Two,MultiSplit                    0.001541
ThreeOrMore,MultiSplit            0.000620
One,MultiSplit                    0.000536
Two,ThreeOrMore                   0.000451
One,ThreeOrMore                   0.000199
One,Two,MultiSplit                0.000030
Two,ThreeOrMore,MultiSplit        0.000014
One,Two,ThreeOrMore               0.000014
One,Two,ThreeOrMore,MultiSplit    0.000005
One,ThreeOrMore,MultiSplit        0.000005
Name: proportion, dtype: float64


In [25]:
# checking for distribution and null values
print(categorical_df.isnull().sum())
categorical_df['Levels'].value_counts(normalize = True)

Flooring                  0
PoolPrivateYN             0
PropertyType              0
PropertySubType           0
City                      0
FireplaceYN               0
Levels                    0
NewConstructionYN    101342
City_freq                 0
dtype: int64


Levels
One                               0.604493
Two                               0.354075
ThreeOrMore                       0.021262
MultiSplit                        0.014466
One,Two                           0.002326
Two,MultiSplit                    0.001527
ThreeOrMore,MultiSplit            0.000618
One,MultiSplit                    0.000535
Two,ThreeOrMore                   0.000444
One,ThreeOrMore                   0.000190
One,Two,MultiSplit                0.000026
Two,ThreeOrMore,MultiSplit        0.000016
One,Two,ThreeOrMore               0.000012
One,ThreeOrMore,MultiSplit        0.000006
One,Two,ThreeOrMore,MultiSplit    0.000004
Name: proportion, dtype: float64

Next, I will perform the binary encoding as mentioned earlier.

In [26]:
categorical_df['Level_One'] = categorical_df['Levels'].apply(lambda x: int('One' in x.split(',')))
categorical_df['Level_Two'] = categorical_df['Levels'].apply(lambda x: int('Two' in x.split(',')))
categorical_df['Level_ThreeOrMore'] = categorical_df['Levels'].apply(lambda x: int('ThreeOrMore' in x.split(',')))
categorical_df['Level_MultiSplit'] = categorical_df['Levels'].apply(lambda x: int('MultiSplit' in x.split(',')))

In [27]:
categorical_df

Flooring  PoolPrivateYN      PropertyType        PropertySubType  \
0          Wood              0       Residential  SingleFamilyResidence   
1         Mixed              0  ResidentialLease  SingleFamilyResidence   
2         Mixed              0  ResidentialLease  SingleFamilyResidence   
3          Wood              0       Residential  SingleFamilyResidence   
4          Wood              0  ResidentialLease  SingleFamilyResidence   
...         ...            ...               ...                    ...   
504752    Mixed              1       Residential  SingleFamilyResidence   
504753     Tile              0       Residential  SingleFamilyResidence   
504754     Wood              0       Residential  SingleFamilyResidence   
504755    Mixed              1       Residential  SingleFamilyResidence   
504756    Mixed              0       Residential  SingleFamilyResidence   

                 City  FireplaceYN       Levels NewConstructionYN  City_freq  \
0       national city            0          Two             False        395   
1         chula vista            1          Two               NaN       2995   
2       newport beach            1          One             False       1959   
3       national city            0          Two             False        395   
4        solana beach            1  ThreeOrMore               NaN        284   
...               ...          ...          ...               ...        ...   
504752         corona            1          Two             False       4873   
504753   yucca valley            1          One             False       1346   
504754          hemet            1          One             False       4493   
504755      riverside            1          One             False       7679   
504756       stockton            1          One               NaN        658   

        Level_One  Level_Two  Level_ThreeOrMore  Level_MultiSplit  
0               0          1                  0                 0  
1               0          1                  0                 0  
2               1          0                  0                 0  
3               0          1                  0                 0  
4               0          0                  1                 0  
...           ...        ...                ...               ...  
504752          0          1                  0                 0  
504753          1          0                  0                 0  
504754          1          0                  0                 0  
504755          1          0                  0                 0  
504756          1          0                  0                 0  

[504757 rows x 13 columns]

In [28]:
print(categorical_df.isnull().sum())

Flooring                  0
PoolPrivateYN             0
PropertyType              0
PropertySubType           0
City                      0
FireplaceYN               0
Levels                    0
NewConstructionYN    101342
City_freq                 0
Level_One                 0
Level_Two                 0
Level_ThreeOrMore         0
Level_MultiSplit          0
dtype: int64


## NewConstructionYN

In [29]:
# Checking distribution
categorical_df['NewConstructionYN'].value_counts()

NewConstructionYN
False    388928
True      14487
Name: count, dtype: int64

Similar to PoolPrivateYN and FirePlaceYN, I will fill in the missing values with probability.

In [30]:
# Defining the probabilities
newconstruction_probabilities = categorical_df['NewConstructionYN'].value_counts(normalize = True)
print(newconstruction_probabilities)

# Filling in missing values based on probability
categorical_df['NewConstructionYN'] = categorical_df['NewConstructionYN'].apply(lambda x: np.random.choice(newconstruction_probabilities.index, p = newconstruction_probabilities.values) if pd.isna(x) else x)


NewConstructionYN
False    0.964089
True     0.035911
Name: proportion, dtype: float64


In [31]:
# Checking for distribution and null values
print(categorical_df.isnull().sum())
categorical_df['NewConstructionYN'].value_counts(normalize=True)

Flooring             0
PoolPrivateYN        0
PropertyType         0
PropertySubType      0
City                 0
FireplaceYN          0
Levels               0
NewConstructionYN    0
City_freq            0
Level_One            0
Level_Two            0
Level_ThreeOrMore    0
Level_MultiSplit     0
dtype: int64


NewConstructionYN
False    0.964199
True     0.035801
Name: proportion, dtype: float64

In [32]:
# Encoding True to 1 and False to 0 to help with training the model
categorical_df['NewConstructionYN'] = categorical_df['NewConstructionYN'].map({True: 1, False: 0})
categorical_df['NewConstructionYN'].value_counts(normalize=True)

NewConstructionYN
0    0.964199
1    0.035801
Name: proportion, dtype: float64

# Checking Categorical Columns

In [33]:
print(categorical_df.isnull().sum())

Flooring             0
PoolPrivateYN        0
PropertyType         0
PropertySubType      0
City                 0
FireplaceYN          0
Levels               0
NewConstructionYN    0
City_freq            0
Level_One            0
Level_Two            0
Level_ThreeOrMore    0
Level_MultiSplit     0
dtype: int64


In [34]:
categorical_df

Flooring  PoolPrivateYN      PropertyType        PropertySubType  \
0          Wood              0       Residential  SingleFamilyResidence   
1         Mixed              0  ResidentialLease  SingleFamilyResidence   
2         Mixed              0  ResidentialLease  SingleFamilyResidence   
3          Wood              0       Residential  SingleFamilyResidence   
4          Wood              0  ResidentialLease  SingleFamilyResidence   
...         ...            ...               ...                    ...   
504752    Mixed              1       Residential  SingleFamilyResidence   
504753     Tile              0       Residential  SingleFamilyResidence   
504754     Wood              0       Residential  SingleFamilyResidence   
504755    Mixed              1       Residential  SingleFamilyResidence   
504756    Mixed              0       Residential  SingleFamilyResidence   

                 City  FireplaceYN       Levels  NewConstructionYN  City_freq  \
0       national city            0          Two                  0        395   
1         chula vista            1          Two                  0       2995   
2       newport beach            1          One                  0       1959   
3       national city            0          Two                  0        395   
4        solana beach            1  ThreeOrMore                  0        284   
...               ...          ...          ...                ...        ...   
504752         corona            1          Two                  0       4873   
504753   yucca valley            1          One                  0       1346   
504754          hemet            1          One                  0       4493   
504755      riverside            1          One                  0       7679   
504756       stockton            1          One                  0        658   

        Level_One  Level_Two  Level_ThreeOrMore  Level_MultiSplit  
0               0          1                  0                 0  
1               0          1                  0                 0  
2               1          0                  0                 0  
3               0          1                  0                 0  
4               0          0                  1                 0  
...           ...        ...                ...               ...  
504752          0          1                  0                 0  
504753          1          0                  0                 0  
504754          1          0                  0                 0  
504755          1          0                  0                 0  
504756          1          0                  0                 0  

[504757 rows x 13 columns]

In [35]:
categorical_df['PropertyType'].value_counts()

PropertyType
Residential          426327
ResidentialLease      77486
ResidentialIncome       944
Name: count, dtype: int64

I will quickly encode these 3 values to 0, 1, or 2, to help with training the model.

In [36]:
categorical_df['PropertyType_Encoded'] = categorical_df['PropertyType'].astype('category').cat.codes

In [37]:
categorical_df


Flooring  PoolPrivateYN      PropertyType        PropertySubType  \
0          Wood              0       Residential  SingleFamilyResidence   
1         Mixed              0  ResidentialLease  SingleFamilyResidence   
2         Mixed              0  ResidentialLease  SingleFamilyResidence   
3          Wood              0       Residential  SingleFamilyResidence   
4          Wood              0  ResidentialLease  SingleFamilyResidence   
...         ...            ...               ...                    ...   
504752    Mixed              1       Residential  SingleFamilyResidence   
504753     Tile              0       Residential  SingleFamilyResidence   
504754     Wood              0       Residential  SingleFamilyResidence   
504755    Mixed              1       Residential  SingleFamilyResidence   
504756    Mixed              0       Residential  SingleFamilyResidence   

                 City  FireplaceYN       Levels  NewConstructionYN  City_freq  \
0       national city            0          Two                  0        395   
1         chula vista            1          Two                  0       2995   
2       newport beach            1          One                  0       1959   
3       national city            0          Two                  0        395   
4        solana beach            1  ThreeOrMore                  0        284   
...               ...          ...          ...                ...        ...   
504752         corona            1          Two                  0       4873   
504753   yucca valley            1          One                  0       1346   
504754          hemet            1          One                  0       4493   
504755      riverside            1          One                  0       7679   
504756       stockton            1          One                  0        658   

        Level_One  Level_Two  Level_ThreeOrMore  Level_MultiSplit  \
0               0          1                  0                 0   
1               0          1                  0                 0   
2               1          0                  0                 0   
3               0          1                  0                 0   
4               0          0                  1                 0   
...           ...        ...                ...               ...   
504752          0          1                  0                 0   
504753          1          0                  0                 0   
504754          1          0                  0                 0   
504755          1          0                  0                 0   
504756          1          0                  0                 0   

        PropertyType_Encoded  
0                          0  
1                          2  
2                          2  
3                          0  
4                          2  
...                      ...  
504752                     0  
504753                     0  
504754                     0  
504755                     0  
504756                     0  

[504757 rows x 14 columns]

I will use binary encoding on the 'flooring' column to create 11 new columns, where the observation will have a value of 1 if they have that value and 0 if not.

In [38]:
categorical_df = pd.get_dummies(categorical_df, columns=['Flooring'], drop_first=True)

In [43]:
# Encoding it from boolean to integers
dummy_cols = [col for col in categorical_df.columns if col.startswith('Flooring_')]
categorical_df[dummy_cols] = categorical_df[dummy_cols].astype(int)


In [57]:
categorical_df.columns

Index(['PoolPrivateYN', 'PropertyType', 'PropertySubType', 'City',
       'FireplaceYN', 'Levels', 'NewConstructionYN', 'City_freq', 'Level_One',
       'Level_Two', 'Level_ThreeOrMore', 'Level_MultiSplit',
       'PropertyType_Encoded', 'Flooring_Brick', 'Flooring_Carpet',
       'Flooring_Concrete', 'Flooring_Laminate', 'Flooring_Mixed',
       'Flooring_SeeRemarks', 'Flooring_Stone', 'Flooring_Tile',
       'Flooring_Vinyl', 'Flooring_Wood'],
      dtype='object')

In [55]:
categorical_df

PoolPrivateYN      PropertyType        PropertySubType           City  \
0                   0       Residential  SingleFamilyResidence  national city   
1                   0  ResidentialLease  SingleFamilyResidence    chula vista   
2                   0  ResidentialLease  SingleFamilyResidence  newport beach   
3                   0       Residential  SingleFamilyResidence  national city   
4                   0  ResidentialLease  SingleFamilyResidence   solana beach   
...               ...               ...                    ...            ...   
504752              1       Residential  SingleFamilyResidence         corona   
504753              0       Residential  SingleFamilyResidence   yucca valley   
504754              0       Residential  SingleFamilyResidence          hemet   
504755              1       Residential  SingleFamilyResidence      riverside   
504756              0       Residential  SingleFamilyResidence       stockton   

        FireplaceYN       Levels  NewConstructionYN  City_freq  Level_One  \
0                 0          Two                  0        395          0   
1                 1          Two                  0       2995          0   
2                 1          One                  0       1959          1   
3                 0          Two                  0        395          0   
4                 1  ThreeOrMore                  0        284          0   
...             ...          ...                ...        ...        ...   
504752            1          Two                  0       4873          0   
504753            1          One                  0       1346          1   
504754            1          One                  0       4493          1   
504755            1          One                  0       7679          1   
504756            1          One                  0        658          1   

        Level_Two  ...  Flooring_Brick  Flooring_Carpet  Flooring_Concrete  \
0               1  ...               0                0                  0   
1               1  ...               0                0                  0   
2               0  ...               0                0                  0   
3               1  ...               0                0                  0   
4               0  ...               0                0                  0   
...           ...  ...             ...              ...                ...   
504752          1  ...               0                0                  0   
504753          0  ...               0                0                  0   
504754          0  ...               0                0                  0   
504755          0  ...               0                0                  0   
504756          0  ...               0                0                  0   

        Flooring_Laminate  Flooring_Mixed  Flooring_SeeRemarks  \
0                       0               0                    0   
1                       0               1                    0   
2                       0               1                    0   
3                       0               0                    0   
4                       0               0                    0   
...                   ...             ...                  ...   
504752                  0               1                    0   
504753                  0               0                    0   
504754                  0               0                    0   
504755                  0               1                    0   
504756                  0               1                    0   

        Flooring_Stone  Flooring_Tile  Flooring_Vinyl  Flooring_Wood  
0                    0              0               0              1  
1                    0              0               0              0  
2                    0              0               0              0  
3                    0              0               0              1  
4                    0   

Next, I will drop the original columns that contain string values so the new dataframe is entirely numerical

In [58]:
columns_to_drop = ['PropertyType', 'PropertySubType', 'City', 'Levels']

categorical_df = categorical_df.drop(columns = columns_to_drop)
categorical_df

PoolPrivateYN  FireplaceYN  NewConstructionYN  City_freq  Level_One  \
0                   0            0                  0        395          0   
1                   0            1                  0       2995          0   
2                   0            1                  0       1959          1   
3                   0            0                  0        395          0   
4                   0            1                  0        284          0   
...               ...          ...                ...        ...        ...   
504752              1            1                  0       4873          0   
504753              0            1                  0       1346          1   
504754              0            1                  0       4493          1   
504755              1            1                  0       7679          1   
504756              0            1                  0        658          1   

        Level_Two  Level_ThreeOrMore  Level_MultiSplit  PropertyType_Encoded  \
0               1                  0                 0                     0   
1               1                  0                 0                     2   
2               0                  0                 0                     2   
3               1                  0                 0                     0   
4               0                  1                 0                     2   
...           ...                ...               ...                   ...   
504752          1                  0                 0                     0   
504753          0                  0                 0                     0   
504754          0                  0                 0                     0   
504755          0                  0                 0                     0   
504756          0                  0                 0                     0   

        Flooring_Brick  Flooring_Carpet  Flooring_Concrete  Flooring_Laminate  \
0                    0                0                  0                  0   
1                    0                0                  0                  0   
2                    0                0                  0                  0   
3                    0                0                  0                  0   
4                    0                0                  0                  0   
...                ...              ...                ...                ...   
504752               0                0                  0                  0   
504753               0                0                  0                  0   
504754               0                0                  0                  0   
504755               0                0                  0                  0   
504756               0                0                  0                  0   

        Flooring_Mixed  Flooring_SeeRemarks  Flooring_Stone  Flooring_Tile  \
0                    0                    0               0              0   
1                    1                    0               0              0   
2                    1                    0               0              0   
3                    0                    0               0              0   
4                    0                    0               0              0   
...                ...                  ...             ...            ...   
504752               1                    0               0              0   
504753               0                    0               0              1   
504754               0                    0               0              0   
504755               1                    0               0              0   
504756               1                    0               0              0   

        Flooring_Vinyl  Flooring_Wood  
0                    0              1  
1                    0              0  
2                    0              0  
3                    0      

In [59]:
# Exporting as a csv file
categorical_df.to_csv('categorical_dataframe_hannah_nguyen_fixed.csv', index = False)